services:
    web:
        container_name: inventory-local
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: dev
            APP_DEBUG: "1"
